#gem 'pg'

development:
  adapter: postgresql
  encoding: unicode
  database: socialye_development
  pool: 5
  host: localhost
  username: pguser
  password: Diamond.1


test:
  adapter: postgresql
  encoding: unicode
  database: socialye_test
  pool: 5
  host: localhost
  username: pguser
  password: Diamond.1


production:
  adapter: postgresql
  encoding: unicode
  database: socialye_production
  host: localhost
  pool: 5
  username: kiran
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>

